### ISSUE TITLE
Reproducing defaults from original ggbiplot extension

### ISSUE THREAD

**Issue by sraul1** [corybrunson/ordr#53] opened 2023-03-13 18:46 UTC
Hey All,

I have been trying to re-create an old figure that used the original [ggbiplot extension](https://github.com/vqv/ggbiplot) to no avail. 

The original figure had default scaling parameters (scale = 1; obs.scale = 1 - scale; var.scale = scale) but I have not been able to translate that to how row/columns are scaled in ordr. It seemed like it would be an easy solution, I'm just not as well-versed in how ordr structures things.

Just thought I would query you all here before making a reprex.

**Comment by corybrunson** [comment] 2023-03-14 12:51
Hi @sraul1, thanks for raising the issue. You're right that exactly reproducing a {ggbiplot} plot can be difficult or impossible in {ordr}; i've illustrated using the example from the README below.

Part of the reason is that {ggbiplot} does some things under the hood that i don't understand or think should be controlled by the user. Specifically, [the circle radius](https://github.com/vqv/ggbiplot/blob/master/R/ggbiplot.r#L105) and [the variable coordinates](https://github.com/vqv/ggbiplot/blob/master/R/ggbiplot.r#L109) are scaled independently of each other, which prevents their useful co-interpretation as projected axes whose lengths and angles approximate fidelity in the plot and correlations, respectively. As a result, most of the arrows almost reach the circumference, which suggests that the vast majority of the variance in the data is captured in these two dimensions. (This is belied by the proportions in the axis labels.) Moreover, the scaling of the variable coordinates is not combined with secondary axes, and as a result their inner product relationship with the observation coordinates is partially lost.

These choices may be well-justified and even common practice among statisticians in this field; i wouldn't necessarily know. The transformations i built in to {ordr} are ones that i knew could apply meaningfully to any SVD-based method. I'd be very glad for a resource on how to best use the chi-squared scaling techniques of {ggbiplot} with other transformations, for example, but i haven't found one yet. In the meantime, i'd be glad to see what plot you're trying to reproduce and offer any suggestions.

``` r
library(ggbiplot)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.2
#> Loading required package: plyr
#> Warning: package 'plyr' was built under R version 4.1.2
#> Loading required package: scales
#> Warning: package 'scales' was built under R version 4.1.2
#> Loading required package: grid
data(wine)
wine.pca <- prcomp(wine, scale. = TRUE)
ggbiplot(wine.pca, obs.scale = 1, var.scale = 1,
         groups = wine.class, ellipse = TRUE, circle = TRUE) +
  scale_color_discrete(name = '') +
  theme(legend.direction = 'horizontal', legend.position = 'top')
```

![](https://i.imgur.com/hdGpfU4.png)

``` r

library(ordr)
#> 
#> Attaching package: 'ordr'
#> The following object is masked from 'package:ggbiplot':
#> 
#>     ggbiplot
wine.pca %>%
  as_tbl_ord() %>%
  augment_ord() %>%
  mutate_rows(class = wine.class) %>%
  ggbiplot(aes(color = class, label = name),
           # note arbitrary choice of scale factor for column elements
           sec.axes = "cols", scale.factor = 5) +
  geom_unit_circle(color = muted("white"), alpha = 1/3, scale.factor = 5) +
  geom_cols_vector(color = "darkred") +
  geom_cols_text_radiate(size = 3, color = "darkred") +
  geom_rows_point() +
  # note that the confidence level is used differently
  stat_rows_ellipse(level = .68)
```

![](https://i.imgur.com/ywpqu3c.png)

<sup>Created on 2023-03-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sraul1** [comment] 2023-03-14 16:06
> Hi @sraul1, thanks for raising the issue. You're right that exactly reproducing a {ggbiplot} plot can be difficult or impossible in {ordr}; i've illustrated using the example from the README below.
> 
> Part of the reason is that {ggbiplot} does some things under the hood that i don't understand or think should be controlled by the user. Specifically, [the circle radius](https://github.com/vqv/ggbiplot/blob/master/R/ggbiplot.r#L105) and [the variable coordinates](https://github.com/vqv/ggbiplot/blob/master/R/ggbiplot.r#L109) are scaled independently of each other, which prevents their useful co-interpretation as projected axes whose lengths and angles approximate fidelity in the plot and correlations, respectively. As a result, most of the arrows almost reach the circumference, which suggests that the vast majority of the variance in the data is captured in these two dimensions. (This is belied by the percentages in the axis labels.) Moreover, the scaling of the variable coordinates is not combined with secondary axes, and as a result their inner product relationship with the observation coordinates is partially lost.
> 
> These choices may be well-justified and even common practice among statisticians in this field; i wouldn't necessarily know. The transformations i built in to {ordr} are ones that i knew could apply meaningfully to any SVD-based method. I'd be very glad for a resource on how to best use the chi-squared scaling techniques of {ggbiplot} with other transformations, for example, but i haven't found one yet. In the meantime, i'd be glad to see what plot you're trying to reproduce and offer any suggestions.
> 
> ```r
> library(ggbiplot)
> #> Loading required package: ggplot2
> #> Warning: package 'ggplot2' was built under R version 4.1.2
> #> Loading required package: plyr
> #> Warning: package 'plyr' was built under R version 4.1.2
> #> Loading required package: scales
> #> Warning: package 'scales' was built under R version 4.1.2
> #> Loading required package: grid
> data(wine)
> wine.pca <- prcomp(wine, scale. = TRUE)
> ggbiplot(wine.pca, obs.scale = 1, var.scale = 1,
>          groups = wine.class, ellipse = TRUE, circle = TRUE) +
>   scale_color_discrete(name = '') +
>   theme(legend.direction = 'horizontal', legend.position = 'top')
> ```
> 
> ![](https://camo.githubusercontent.com/6473d19ff873649f2ae8dc959ef4e21cf22cb4cdc08190d3ff4b50e6ee89a1e1/68747470733a2f2f692e696d6775722e636f6d2f395978337838492e706e67)
> 
> ```r
> library(ordr)
> #> 
> #> Attaching package: 'ordr'
> #> The following object is masked from 'package:ggbiplot':
> #> 
> #>     ggbiplot
> wine.pca %>%
>   as_tbl_ord() %>%
>   augment_ord() %>%
>   mutate_rows(class = wine.class) %>%
>   ggbiplot(aes(color = class, label = name),
>            # note arbitrary choice of scale factor for column elements
>            sec.axes = "cols", scale.factor = 5) +
>   geom_unit_circle(color = muted("white"), alpha = 1/3, scale.factor = 5) +
>   geom_cols_vector(color = "darkred") +
>   geom_cols_text_radiate(size = 3, color = "darkred") +
>   geom_rows_point() +
>   # note that the confidence level is used differently
>   stat_rows_ellipse(level = .68) +
>   scale_color_discrete(name = "") +
>   theme(legend.direction = "horizontal", legend.position = "top")
> ```
> 
> ![](https://camo.githubusercontent.com/27068345696f6c6a06096d0b4f349177bb98a8aa635b9f85a17fd498f494e2a5/68747470733a2f2f692e696d6775722e636f6d2f6e5369397144522e706e67)
> 
> Created on 2023-03-14 with [reprex v2.0.2](https://reprex.tidyverse.org)

**Comment by corybrunson** [comment] 2023-03-14 16:33
OK! I'll reopen it now and watch out for the reprex.

**Comment by corybrunson** [comment] 2023-07-05 10:12
Hi @sraul1, i'm closing this issue to help focus on open needs, but please do reopen it if and when you have some example code or have any follow-up issues!

**Closed by corybrunson** 2023-07-05 10:12 UTC
